export interface IProps {
  rootClassName?: string;
  nameValue: string;
  phoneValue: number | null;
  cityValue: string;
  streetValue: string;
  houseValue: string;
  entranceValue: string;
  apartmentValue: string;
  emailValue: string;
  isSubscribeValue: boolean;
  apartmentError?: string;
  cityError?: string;
  emailError?: string;
  entranceError?: string;
  houseError?: string;
  nameError?: string;
  phoneError?: string;
  streetError?: string;
  isSubscribeError?: string;
  isChanging: boolean;
  isLoadingPatchProfile: boolean;
  isLoadingProfile?: boolean;
  isAuth: boolean;
  cbChangeTouchedApartment: () => void;
  cbChangeTouchedCity: () => void;
  cbChangeTouchedEmail: () => void;
  cbChangeTouchedEntrance: () => void;
  cbChangeTouchedHouse: () => void;
  cbChangeTouchedName: () => void;
  cbChangeTouchedPhone: () => void;
  cbChangeTouchedStreet: () => void;
  cbChangeTouchedIsSubscribe: () => void;
  cbChangeApartmentValue: (value: string) => void;
  cbChangeCityValue: (value: string) => void;
  cbChangeEmailValue: (value: string) => void;
  cbChangeEntranceValue: (value: string) => void;
  cbChangeHouseValue: (value: string) => void;
  cbChangeNameValue: (value: string) => void;
  cbChangePhoneValue: (value: number | null) => void;
  cbChangeStreetValue: (value: string) => void;
  cbChangeIsSubscribeValue: (value: boolean) => void;
  cbOnChange: () => void;
  cbOnChangeCancel: () => void;
  cbOnChangeSave: () => void;
  cbLogout: () => void;
}
